# Generated by Django 5.0.6 on 2024-05-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='taskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PM1_1', models.BooleanField(default=False)),
                ('PM1_2', models.BooleanField(default=False)),
                ('PM1_3', models.BooleanField(default=False)),
            ],
        ),
    ]
