# Generated by Django 5.0.6 on 2024-06-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guiadevopsapp', '0002_codificacionmodel_construccionmodel_desplieguemodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lanzamientoModel',
            new_name='liberacionModel',
        ),
    ]
