# Generated by Django 5.0.6 on 2024-08-06 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiadevopsapp', '0003_rename_lanzamientomodel_liberacionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codificacionherramientasmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.TextField()),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('toolCV', models.BooleanField(default=False, verbose_name='Control de Versiones (Git, GitHub, GitLab, Mercurial, Subversion (SVN), BitBucket Atlassian)')),
                ('toolIDE', models.BooleanField(default=False, verbose_name='Entorno de Desarrollo Integrado (IDE) (Visual Studio Code, Eclipse, NetBeans, Android Studio)')),
            ],
            options={
                'get_latest_by': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Construccionherramientasmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.TextField()),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('toolCE', models.BooleanField(default=False, verbose_name='Compilación o empaquetado (Maven, Gradle, Apache Ant, Make)')),
            ],
            options={
                'get_latest_by': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Despliegueherramientasmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.TextField()),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('toolCD', models.BooleanField(default=False, verbose_name='Despliegue Continuo (GitLab, CodeShip, BitBucket Pipelines, Puppet Pipelines for Applications, Atlassian Bamboo, AWS OpsWorks)')),
                ('toolGC', models.BooleanField(default=False, verbose_name='Gestión de la Configuración (Ansible, Puppet, Chef, AWS Opsworks, SaltStack)')),
                ('toolIaC', models.BooleanField(default=False, verbose_name='Infraestructura como Código (Chef, Terraform, Ansible, Pulumi, AWS CloudFormation, Azure ARM Templates, Google Cloud Deployment Manager)')),
                ('toolC', models.BooleanField(default=False, verbose_name='Contenedorización (Docker, Podman)')),
                ('toolSN', models.BooleanField(default=False, verbose_name='Servicios en la Nube (Heroku, Microsoft Azure, AWS, Google Cloud Platform, Oracle Cloud, OpenShift)')),
            ],
            options={
                'get_latest_by': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Liberacionherramientasmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.TextField()),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('toolCI', models.BooleanField(default=False, verbose_name='Integración Continua (Jenkins, Travis CI, CircleCI, GitLab CI, Atlassian Bamboo, CodeShip, BitBucket Cloud Atlassian, Puppet Pipelines for Applications)')),
                ('toolGA', models.BooleanField(default=False, verbose_name='Gestión de Artefactos (Sonatype Nexus Repository, JFrog Artifactory, GitHub Packages)')),
            ],
            options={
                'get_latest_by': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Monitoreoherramientasmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.TextField()),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('toolMR', models.BooleanField(default=False, verbose_name='Monitoreo de Redes (ManageEngine OpManager, Nagios, New Relic, Microsoft\u202fSCOM, Sensu, DataDog, ExtraHop, SignalFX, SumoLogic)')),
                ('toolAD', models.BooleanField(default=False, verbose_name='Análisis de Datos (ManageEngine OpManager , Splunk, ELK Stack, New Relic, Microsoft\u202fSCOM, DataDog, SignalFX, SumoLogic)')),
                ('toolGL', models.BooleanField(default=False, verbose_name='Gestión de Logs (ManageEngine OpManager , Splunk, ELK Stack, New Relic, Microsoft\u202fSCOM, SumoLogic, Scalyr, Loggly)')),
                ('toolAPM', models.BooleanField(default=False, verbose_name='Monitoreo de Aplicaciones (New Relic, Microsoft\u202fSCOM, Sensu, DataDog, ExtraHop, SignalFX, Dynatrace, AppDynamics)')),
                ('toolUXM', models.BooleanField(default=False, verbose_name='Monitoreo de Experiencia de Usuario (ManageEngine OpManager, New Relic, ExtraHop, Dynatrace, AppDynamics)')),
            ],
            options={
                'get_latest_by': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Operacionesherramientasmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.TextField()),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('toolOC', models.BooleanField(default=False, verbose_name='Orquestación de Contenedores (Kubernetes, MESOSPHERE DC/OS, Docker Enterprise (Swarm))')),
                ('toolGC', models.BooleanField(default=False, verbose_name='Gestión de la Configuración (Ansible, Puppet, Chef, AWS Opsworks, SaltStack)')),
                ('toolIaC', models.BooleanField(default=False, verbose_name='Infraestructura como Código (Chef, Terraform, Ansible, Pulumi, AWS CloudFormation, Azure ARM Templates, Google Cloud Deployment Manager)')),
                ('toolGS', models.BooleanField(default=False, verbose_name='Gestión de Servicios (Atlassian Jira Service Management)')),
                ('toolGI', models.BooleanField(default=False, verbose_name='Gestión de Incidentes (Atlassian Jira Service Management, BigPanda, VictorOps, PagerDuty, OpsGenie)')),
            ],
            options={
                'get_latest_by': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Planificacionherramientasmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.TextField()),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('toolGT', models.BooleanField(default=False, verbose_name='Gestión de Tareas (GitLab, Jira software, ClickUP, Bitrix24)')),
            ],
            options={
                'get_latest_by': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Pruebasherramientasmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.TextField()),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('toolA', models.BooleanField(default=False, verbose_name='Automatización (Selenium, Jasmine, Karma, Appium, Postman, Robot Framework)')),
                ('toolCP', models.BooleanField(default=False, verbose_name='Creación de Pruebas (PyTest, Junit, NUnit, TestNG, Cucumber, Jasmine, Robot Framework, Appium, Postman)')),
                ('toolAEC', models.BooleanField(default=False, verbose_name='Análisis estático de código (ESLint, Pylint, RuboCop, Stylelint, Flake8, SonarQube)')),
                ('toolPU', models.BooleanField(default=False, verbose_name='Pruebas Unitarias (JUnit, NUnit, TestNG, PyTest, Jasmine, Karma)')),
                ('toolPI', models.BooleanField(default=False, verbose_name='Pruebas de Integración (PyTest, TestNG, Postman, Appium, Robot Framework)')),
                ('toolPR', models.BooleanField(default=False, verbose_name='Pruebas de Regresión (JUnit, TestNG)')),
            ],
            options={
                'get_latest_by': ['fecha'],
            },
        ),
    ]
