# Generated by Django 5.0.6 on 2024-09-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiadevopsapp', '0005_rename_codificacionmodel_codificaciontareasmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codificacionherramientasmodel',
            name='toolGA',
            field=models.BooleanField(default=False, verbose_name='Gestión de Artefactos (AWS CodeArtifact, Harbor, GitHub Packages, Azure Artifacts, Sonatype Nexus Repository, JFrog Artifactory)'),
        ),
        migrations.AlterField(
            model_name='construccionherramientasmodel',
            name='toolCE',
            field=models.BooleanField(default=False, verbose_name='Compilación o empaquetado (Maven, Gradle, Apache Ant, Make, Webpack, CMake, MSBuild)'),
        ),
        migrations.AlterField(
            model_name='despliegueherramientasmodel',
            name='toolCD',
            field=models.BooleanField(default=False, verbose_name='Despliegue Continuo (GitLab CI/CD, GitHub Actions, Bitbucket Pipelines, Puppet Pipelines for Applications, Atlassian Bamboo, CodeShip, AWS Opsworks)'),
        ),
        migrations.AlterField(
            model_name='despliegueherramientasmodel',
            name='toolIaC',
            field=models.BooleanField(default=False, verbose_name='Infraestructura como Código (Terraform, Chef, Ansible, Pulumi, AWS CloudFormation, Azure ARM Templates, Google Cloud Deployment Manager)'),
        ),
        migrations.AlterField(
            model_name='despliegueherramientasmodel',
            name='toolSN',
            field=models.BooleanField(default=False, verbose_name='Servicios en la Nube (AWS, Heroku, Microsoft Azure, Google Cloud Platform, Oracle Cloud, OpenShift)'),
        ),
        migrations.AlterField(
            model_name='liberacionherramientasmodel',
            name='toolCI',
            field=models.BooleanField(default=False, verbose_name='Integración Continua (GitLab CI/CD, GitHub Actions, BitBucket Cloud Atlassian, Puppet Pipelines for Applications, Atlassian Bamboo, CodeShip, Jenkins, CircleCI, Travis CI)'),
        ),
        migrations.AlterField(
            model_name='liberacionherramientasmodel',
            name='toolGA',
            field=models.BooleanField(default=False, verbose_name='Gestión de Artefactos (AWS CodeArtifact, Harbor, GitHub Packages, Azure Artifacts, Sonatype Nexus Repository, JFrog Artifactory)'),
        ),
        migrations.AlterField(
            model_name='monitoreoherramientasmodel',
            name='toolAPM',
            field=models.BooleanField(default=False, verbose_name='Monitoreo de Aplicaciones (Prometheus, New Relic, Microsoft\u202fSCOM, Sensu, DataDog, ExtraHop, SignalFX, Dynatrace, AppDynamics)'),
        ),
        migrations.AlterField(
            model_name='operacionesherramientasmodel',
            name='toolIaC',
            field=models.BooleanField(default=False, verbose_name='Infraestructura como Código (Terraform, Chef, Ansible, Pulumi, AWS CloudFormation, Azure ARM Templates, Google Cloud Deployment Manager)'),
        ),
        migrations.AlterField(
            model_name='operacionesherramientasmodel',
            name='toolOC',
            field=models.BooleanField(default=False, verbose_name='Orquestación de Contenedores (Kubernetes, Docker Swarm, MESOSPHERE DC/OS)'),
        ),
        migrations.AlterField(
            model_name='planificacionherramientasmodel',
            name='toolGT',
            field=models.BooleanField(default=False, verbose_name='Gestión de Tareas (GitLab, Jira software, ClickUP, Bitrix24, Assana, Trello)'),
        ),
    ]
