# Generated by Django 5.0.6 on 2025-03-18 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiadevopsapp', '0006_codificacionherramientasmodel_toolga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codificacionherramientasmodel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiadevopsapp.usuariomodel'),
        ),
        migrations.AlterField(
            model_name='codificaciontareasmodel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiadevopsapp.usuariomodel'),
        ),
        migrations.AlterField(
            model_name='construccionherramientasmodel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiadevopsapp.usuariomodel'),
        ),
        migrations.AlterField(
            model_name='construcciontareasmodel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiadevopsapp.usuariomodel'),
        ),
        migrations.AlterField(
            model_name='despliegueherramientasmodel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiadevopsapp.usuariomodel'),
        ),
        migrations.AlterField(
            model_name='desplieguetareasmodel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiadevopsapp.usuariomodel'),
        ),
        migrations.AlterField(
            model_name='liberacionherramientasmodel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiadevopsapp.usuariomodel'),
        ),
        migrations.AlterField(
            model_name='liberaciontareasmodel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiadevopsapp.usuariomodel'),
        ),
        migrations.AlterField(
            model_name='monitoreoherramientasmodel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiadevopsapp.usuariomodel'),
        ),
        migrations.AlterField(
            model_name='monitoreotareasmodel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiadevopsapp.usuariomodel'),
        ),
        migrations.AlterField(
            model_name='operacionesherramientasmodel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiadevopsapp.usuariomodel'),
        ),
        migrations.AlterField(
            model_name='operacionestareasmodel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiadevopsapp.usuariomodel'),
        ),
        migrations.AlterField(
            model_name='planificacionherramientasmodel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiadevopsapp.usuariomodel'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiadevopsapp.usuariomodel'),
        ),
        migrations.AlterField(
            model_name='pruebasherramientasmodel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiadevopsapp.usuariomodel'),
        ),
        migrations.AlterField(
            model_name='pruebastareasmodel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiadevopsapp.usuariomodel'),
        ),
    ]
