# Generated by Django 5.0.6 on 2025-07-06 02:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guiadevopsapp', '0007_alter_codificacionherramientasmodel_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacionherramientasmodel',
            name='toolGT',
            field=models.BooleanField(default=False, verbose_name='Task Management (GitLab, Jira software, ClickUP, Bitrix24, Assana, Trello)'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS11',
            field=models.BooleanField(default=False, verbose_name='SI.1.1 Review the current Project Plan with the Work Team members to achieve a common understanding and secure their commitment to the project.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS12',
            field=models.BooleanField(default=False, verbose_name='SI.1.2 Establish or update the implementation environment.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS21',
            field=models.BooleanField(default=False, verbose_name='SI.2.1 Assign tasks to Work Team members according to their role, based on the current Project Plan.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS22',
            field=models.BooleanField(default=False, verbose_name='SI.2.2 Document or update the Requirements Specification.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS23',
            field=models.BooleanField(default=False, verbose_name='SI.2.3 Verify and obtain approval of the Requirements Specification.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS24',
            field=models.BooleanField(default=False, verbose_name='SI.2.4 Validate and obtain approval of the Requirements Specification.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS25',
            field=models.BooleanField(default=False, verbose_name='SI.2.5 Document the draft version of the *Software User Documentation or update this manual, if applicable. *(Optional)'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS26',
            field=models.BooleanField(default=False, verbose_name='SI.2.6 Review and obtain approval of the *Software User Documentation, if applicable. *(Optional)'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS27',
            field=models.BooleanField(default=False, verbose_name='SI.2.7 Incorporate the Requirements Specification and *Software User Documentation into the Software Configuration in the baseline. *(Optional)'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS31',
            field=models.BooleanField(default=False, verbose_name='SI.3.1 Assign tasks to the Work Team members related to their role according to the current Project Plan.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS32',
            field=models.BooleanField(default=False, verbose_name='SI.3.2 Understand the requirements specification.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS33',
            field=models.BooleanField(default=False, verbose_name='SI.3.3 Document or update the Software Design.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS34',
            field=models.BooleanField(default=False, verbose_name='SI.3.4 Verify and obtain approval of the Software Design.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS35',
            field=models.BooleanField(default=False, verbose_name='SI.3.5 Establish or update Test Cases and Test Procedures for integration testing based on the Requirements Specification and the Software Design. The customer provides test data, if necessary.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS36',
            field=models.BooleanField(default=False, verbose_name='SI.3.6 Verify and obtain approval of the Test Cases and Test Procedures.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS37',
            field=models.BooleanField(default=False, verbose_name='SI.3.7 Update the Traceability Record incorporating the Test Cases and Test Procedures.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS38',
            field=models.BooleanField(default=False, verbose_name='SI.3.8 Incorporate the Software Design and Traceability Log into the Software Configuration as part of the baseline. Incorporate Test Cases and Test Procedures into the Project Repository.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS41',
            field=models.BooleanField(default=False, verbose_name='SI.4.1 Assign Tasks to Work Team members related to their role, according to the current Project Plan.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS42',
            field=models.BooleanField(default=False, verbose_name='SI.4.2 Understand the software design.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS43',
            field=models.BooleanField(default=False, verbose_name='SI.4.3 Build or update Software Components based on the detailed part of the Software Design.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS44',
            field=models.BooleanField(default=False, verbose_name='SI.4.4 Design or update unit test cases.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS46',
            field=models.BooleanField(default=False, verbose_name='SI.4.6 Update the Traceability Log by incorporating built or modified Software Components.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS47',
            field=models.BooleanField(default=False, verbose_name='SI.4.7 Incorporate Software Components and Traceability Log into the Software Configuration as part of the baseline.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS51',
            field=models.BooleanField(default=False, verbose_name='SI.5.1 Assign tasks to team members related to their role, according to the current Project Plan.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS510',
            field=models.BooleanField(default=False, verbose_name='SI.5.10 Verify and obtain approval of the *Software User Documentation, if applicable (see SI.5.9)'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS511',
            field=models.BooleanField(default=False, verbose_name='SI.5.11 Incorporate Test Cases and Test Procedures, Software, Traceability Log, Test Report, *Product Operation Guide, and *Software User Documentation into the Software Configuration as part of the baseline. *(Optional)'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS52',
            field=models.BooleanField(default=False, verbose_name='SI.5.2 Understand test cases and test procedures. Establish or update the test environment.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS53',
            field=models.BooleanField(default=False, verbose_name='SI.5.3 Update test cases and test procedures for integration tests, as needed.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS56',
            field=models.BooleanField(default=False, verbose_name='SI.5.6 Update the Traceability Log, if applicable.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS57',
            field=models.BooleanField(default=False, verbose_name='SI.5.7 Document the *Product Operation Guide or update the current guide, if applicable. *(Optional)'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS58',
            field=models.BooleanField(default=False, verbose_name='SI.5.8 Verify and obtain approval of the *Product Operation Guide, if applicable (see SI.5.7)'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS59',
            field=models.BooleanField(default=False, verbose_name='SI.5.9 Document the *Software User Documentation or update the current one, if applicable. *(Optional)'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS61',
            field=models.BooleanField(default=False, verbose_name='SI.6.1 Assign tasks to team members related to their role, according to the current Project Plan.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS62',
            field=models.BooleanField(default=False, verbose_name='SI.6.2 Understand the software configuration.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS63',
            field=models.BooleanField(default=False, verbose_name='SI.6.3 Document the Maintenance Documentation or update the current one.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS64',
            field=models.BooleanField(default=False, verbose_name='SI.6.4 Verify and obtain approval of the Maintenance Documentation.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1IS65',
            field=models.BooleanField(default=False, verbose_name='SI.6.5 Incorporate the Maintenance Documentation as the basis for the Software Configuration.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM11',
            field=models.BooleanField(default=False, verbose_name='PM.1.1 Review the Statement of Work.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM110',
            field=models.BooleanField(default=False, verbose_name='PM.1.10 Document the Version Control Strategy in the Project Plan.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM111',
            field=models.BooleanField(default=False, verbose_name='PM.1.11 Generate the Project Plan integrating the previously identified and documented elements.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM112',
            field=models.BooleanField(default=False, verbose_name='PM.1.12 Include a description of the product, scope, objectives, and deliverables in the project plan.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM113',
            field=models.BooleanField(default=False, verbose_name='PM.1.13 Review and approve the Project Plan.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM114',
            field=models.BooleanField(default=False, verbose_name='PM.1.14 Review and accept the Project Plan.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM115',
            field=models.BooleanField(default=False, verbose_name='PM.1.15 Establish the Project Repository using the Version Control Strategy.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM12',
            field=models.BooleanField(default=False, verbose_name='PM.1.2 Define with the Client the Delivery Instructions for each of the Deliverables specified in the Statement of Work.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM13',
            field=models.BooleanField(default=False, verbose_name='PM.1.3 Identify the specific Tasks to be performed to produce the Deliverables and their Software Components identified in the Statement of Work. Include Tasks in the SI process along with verification, validation, and reviews with Client and Task Team Tasks to ensure the quality of the work products. Identify the Tasks to carry out the Delivery Instructions. Document the tasks.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM14',
            field=models.BooleanField(default=False, verbose_name='PM.1.4 Establish the Estimated Duration to perform each task.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM15',
            field=models.BooleanField(default=False, verbose_name='PM.1.5 Identify and document Resources: human, materials, equipment and tools, standards, including the required training of the Work Team to carry out the project. Include in the schedule the dates by which resources and training will be needed.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM16',
            field=models.BooleanField(default=False, verbose_name='PM.1.6 Establish the Composition of the Work Team by assigning roles and responsibilities according to the Resources.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM17',
            field=models.BooleanField(default=False, verbose_name='PM.1.7 Assign estimated start and end dates for each of the Tasks to create the Project Task Schedule, taking into account the assigned Resources, sequence, and task dependencies.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM18',
            field=models.BooleanField(default=False, verbose_name='PM.1.8 Calculate and document the estimated effort and cost of the project.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM19',
            field=models.BooleanField(default=False, verbose_name='PM.1.9 Identify and document risks that may affect the project.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM21',
            field=models.BooleanField(default=False, verbose_name='PM.2.1 Record actuals in the Progress Status Log.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM22',
            field=models.BooleanField(default=False, verbose_name='PM.2.2 Analyze and evaluate the Change Request in terms of cost, schedule, and technical impact.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM23',
            field=models.BooleanField(default=False, verbose_name='PM.2.3 Conduct review meetings with the Work Team, identify issues, review risk status, and record agreements.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM24',
            field=models.BooleanField(default=False, verbose_name='PM.2.4 Conduct review meetings with the Client, record agreements.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM25',
            field=models.BooleanField(default=False, verbose_name='PM.2.5 Perform backups according to the Version Control Strategy.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM26',
            field=models.BooleanField(default=False, verbose_name='PM.2.6 Perform Project Repository recovery using the Project Repository Backup, if necessary.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM31',
            field=models.BooleanField(default=False, verbose_name='PM.3.1 Evaluate project progress against the Project Plan, comparing: - Actual tasks with planned tasks - Actual results with established project objectives - Actual resource allocation with planned resources - Actual cost with budget estimates - Actual time with planned schedule - Actual risk with previously identified risk.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM32',
            field=models.BooleanField(default=False, verbose_name='PM.3.2 Establish actions to correct deviations or issues and identified risks related to compliance with the plan, as necessary, and document them in the Correction Log.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM33',
            field=models.BooleanField(default=False, verbose_name='PM.3.3 Identify changes to the requirements and/or Project Plan to address significant deviations, potential risks, or issues related to plan compliance, and document them in a Change Request.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM41',
            field=models.BooleanField(default=False, verbose_name='PM.4.1 Formalize project completion in accordance with the Delivery Instructions established in the Project Plan, providing acceptance support and signing the Acceptance Certificate.'),
        ),
        migrations.AlterField(
            model_name='planificaciontareasmodel',
            name='task1PM42',
            field=models.BooleanField(default=False, verbose_name='PM.4.2 Update the Project Repository.'),
        ),
        migrations.CreateModel(
            name='PlanificacionherramientasmodelTENERLO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('toolGT', models.BooleanField(default=False, verbose_name='Gestión de Tareas (GitLab, Jira software, ClickUP, Bitrix24, Assana, Trello)')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiadevopsapp.usuariomodel')),
            ],
            options={
                'get_latest_by': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='PlanificaciontareasmodelTENERLO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('task1PM11', models.BooleanField(default=False, verbose_name='PM.1.1 Revisar la Declaración de Trabajo.')),
                ('task1PM12', models.BooleanField(default=False, verbose_name='PM.1.2 Definir con el Cliente las Instrucciones de Entrega de cada uno de los Entregables especificados en la Declaración de Trabajo.')),
                ('task1PM13', models.BooleanField(default=False, verbose_name='PM.1.3 Identificar las Tareas específicas a realizar para producir los Entregables y sus Componentes de Software identificados en la Declaración de Trabajo. Incluir Tareas en el proceso SI junto con verificación, validación y revisiones con Tareas del Cliente y del Equipo de Trabajo para asegurar la calidad de los productos de trabajo. Identificar las Tareas para realizar las Instrucciones de Entrega. Documente las tareas.')),
                ('task1PM14', models.BooleanField(default=False, verbose_name='PM.1.4 Establecer la Duración Estimada para realizar cada tarea.')),
                ('task1PM15', models.BooleanField(default=False, verbose_name='PM.1.5 Identificar y documentar los Recursos: humanos, materiales, equipos y herramientas, estándares, incluyendo la capacitación requerida del Equipo de Trabajo para realizar el proyecto. Incluya en el cronograma las fechas en las que se necesitarán recursos y capacitación.')),
                ('task1PM16', models.BooleanField(default=False, verbose_name='PM.1.6 Establecer la Composición del Equipo de Trabajo asignando roles y responsabilidades de acuerdo a los Recursos.')),
                ('task1PM17', models.BooleanField(default=False, verbose_name='PM.1.7 Asignar fechas estimadas de inicio y finalización de cada una de las Tareas para crear el Cronograma de las Tareas del Proyecto teniendo en cuenta los Recursos asignados, secuencia y dependencia de las Tareas.')),
                ('task1PM18', models.BooleanField(default=False, verbose_name='PM.1.8 Calcular y documentar el Esfuerzo y Costo Estimado del proyecto.')),
                ('task1PM19', models.BooleanField(default=False, verbose_name='PM.1.9 Identificar y documentar los riesgos que puedan afectar el proyecto.')),
                ('task1PM110', models.BooleanField(default=False, verbose_name='PM.1.10 Documentar la Estrategia de Control de Versiones en el Plan del Proyecto.')),
                ('task1PM111', models.BooleanField(default=False, verbose_name='PM.1.11 Generar el Plan del Proyecto integrando los elementos previamente identificados y documentados.')),
                ('task1PM112', models.BooleanField(default=False, verbose_name='PM.1.12 Incluir descripción del producto, alcance, objetivos y entregables en el plan del proyecto.')),
                ('task1PM113', models.BooleanField(default=False, verbose_name='PM.1.13 Verificar y obtener la aprobación del Plan del Proyecto.')),
                ('task1PM114', models.BooleanField(default=False, verbose_name='PM.1.14 Revisar y aceptar el Plan del Proyecto.')),
                ('task1PM115', models.BooleanField(default=False, verbose_name='PM.1.15 Establecer el Repositorio de Proyectos utilizando la Estrategia de Control de Versiones.')),
                ('task1PM21', models.BooleanField(default=False, verbose_name='PM.2.1 Registre los datos reales en el Registro de estado de progreso.')),
                ('task1PM22', models.BooleanField(default=False, verbose_name='PM.2.2 Analizar y evaluar la Solicitud de Cambio en términos de costo, cronograma e impacto técnico.')),
                ('task1PM23', models.BooleanField(default=False, verbose_name='PM.2.3 Realizar reuniones de revisión con el Equipo de Trabajo, identificar problemas, revisar estado de riesgos, registrar acuerdos.')),
                ('task1PM24', models.BooleanField(default=False, verbose_name='PM.2.4 Realizar reuniones de revisión con el Cliente, registrar acuerdos.')),
                ('task1PM25', models.BooleanField(default=False, verbose_name='PM.2.5 Realizar respaldo de acuerdo a la Estrategia de Control de Versiones.')),
                ('task1PM26', models.BooleanField(default=False, verbose_name='PM.2.6 Realizar la recuperación del Repositorio de Proyectos utilizando la Copia de Seguridad del Repositorio de Proyectos, si es necesario.')),
                ('task1PM31', models.BooleanField(default=False, verbose_name='PM.3.1 Evaluar el progreso del proyecto con respecto al Plan del Proyecto, comparando: - Tareas reales con las Tareas planificadas - Resultados reales con los Objetivos establecidos del proyecto - Asignación de recursos reales con los Recursos planificados - Costo real con las estimaciones presupuestarias - Tiempo real con el cronograma planificado - Riesgo real contra previamente identificado.')),
                ('task1PM32', models.BooleanField(default=False, verbose_name='PM.3.2 Establecer acciones para corregir desviaciones o problemas y riesgos identificados relacionados con el cumplimiento del plan, según sea necesario, documentarlos en el Registro de Corrección.')),
                ('task1PM33', models.BooleanField(default=False, verbose_name='PM.3.3 Identificar cambios a los requisitos y/o Plan del Proyecto para abordar desviaciones importantes, riesgos potenciales o problemas relacionados con el cumplimiento del plan, documentarlos en Solicitud de Cambio.')),
                ('task1PM41', models.BooleanField(default=False, verbose_name='PM.4.1 Formalizar la finalización del proyecto de acuerdo con las Instrucciones de Entrega establecidas en el Plan de Proyecto, brindando soporte de aceptación y firma del Acta de Aceptación.')),
                ('task1PM42', models.BooleanField(default=False, verbose_name='PM.4.2 Actualizar el Repositorio de Proyectos.')),
                ('task1IS11', models.BooleanField(default=False, verbose_name='SI.1.1 Revisión del Plan de Proyecto vigente con los miembros del Equipo de Trabajo para lograr un entendimiento común y lograr su compromiso con el proyecto.')),
                ('task1IS12', models.BooleanField(default=False, verbose_name='SI.1.2 Establecer o actualizar el entorno de implementación.')),
                ('task1IS21', models.BooleanField(default=False, verbose_name='SI.2.1 Asignar Tareas a los miembros del Equipo de Trabajo de acuerdo con su rol, con base en el Plan de Proyecto vigente.')),
                ('task1IS22', models.BooleanField(default=False, verbose_name='SI.2.2 Documentar o actualizar la Especificación de Requisitos.')),
                ('task1IS23', models.BooleanField(default=False, verbose_name='SI.2.3 Verificar y obtener la aprobación de la Especificación de Requisitos.')),
                ('task1IS24', models.BooleanField(default=False, verbose_name='SI.2.4 Validar y obtener aprobación de la Especificación de Requisitos')),
                ('task1IS25', models.BooleanField(default=False, verbose_name='SI.2.5 Documentar la versión preliminar de la *Documentación de Usuario del Software o actualizar el presente manual, si corresponde. *(Opcional)')),
                ('task1IS26', models.BooleanField(default=False, verbose_name='SI.2.6 Verificar y obtener aprobación de la *Documentación del Usuario del Software, en su caso. *(Opcional)')),
                ('task1IS27', models.BooleanField(default=False, verbose_name='SI.2.7 Incorporar la Especificación de Requisitos y la *Documentación de Usuario del Software a la Configuración del Software en la línea base. *(Opcional)')),
                ('task1IS31', models.BooleanField(default=False, verbose_name='SI.3.1 Asignar Tareas a los miembros del Equipo de Trabajo relacionadas con su rol de acuerdo al Plan de Proyecto vigente.')),
                ('task1IS32', models.BooleanField(default=False, verbose_name='SI.3.2 Comprender la especificación de requisitos.')),
                ('task1IS33', models.BooleanField(default=False, verbose_name='SI.3.3 Documentar o actualizar el Diseño del Software.')),
                ('task1IS34', models.BooleanField(default=False, verbose_name='SI.3.4 Verificar y obtener aprobación del Diseño de Software.')),
                ('task1IS35', models.BooleanField(default=False, verbose_name='SI.3.5 Establecer o actualizar Casos de Prueba y Procedimientos de Prueba para pruebas de integración basados \u200b\u200ben la Especificación de Requisitos y el Diseño de Software. El cliente proporciona datos de prueba, si es necesario.')),
                ('task1IS36', models.BooleanField(default=False, verbose_name='SI.3.6 Verificar y obtener aprobación de los Casos de Prueba y Procedimientos de Prueba.')),
                ('task1IS37', models.BooleanField(default=False, verbose_name='SI.3.7 Actualizar el Registro de Trazabilidad incorporando los Casos de Prueba y Procedimientos de Prueba.')),
                ('task1IS38', models.BooleanField(default=False, verbose_name='SI.3.8 Incorporar el Diseño del Software y Registro de Trazabilidad a la Configuración del Software como parte de la línea base. Incorporar los Casos de Prueba y Procedimientos de Prueba al Repositorio de Proyectos.')),
                ('task1IS41', models.BooleanField(default=False, verbose_name='SI.4.1 Asignar Tareas a los miembros del Equipo de Trabajo relacionadas con su rol, de acuerdo al Plan de Proyecto vigente.')),
                ('task1IS42', models.BooleanField(default=False, verbose_name='SI.4.2 Comprender el diseño de software.')),
                ('task1IS43', models.BooleanField(default=False, verbose_name='SI.4.3 Construir o actualizar Componentes de Software con base en la parte detallada del Diseño de Software.')),
                ('task1IS44', models.BooleanField(default=False, verbose_name='SI.4.4 Diseñar o actualizar casos de prueba unitarios.')),
                ('task1IS46', models.BooleanField(default=False, verbose_name='SI.4.6 Actualizar el Registro de Trazabilidad incorporando Componentes de Software construidos o modificados.')),
                ('task1IS47', models.BooleanField(default=False, verbose_name='SI.4.7 Incorporar Componentes de Software y Registro de Trazabilidad a la Configuración del Software como parte de la línea base.')),
                ('task1IS51', models.BooleanField(default=False, verbose_name='SI.5.1 Asignar Tareas a los miembros del equipo de trabajo relacionadas con su rol, de acuerdo al Plan de Proyecto vigente.')),
                ('task1IS52', models.BooleanField(default=False, verbose_name='SI.5.2 Comprender los casos de prueba y los procedimientos de prueba. Establezca o actualice el entorno de prueba.')),
                ('task1IS53', models.BooleanField(default=False, verbose_name='SI.5.3 Actualiza casos de prueba y procedimientos de prueba para pruebas de integración, según sea necesario.')),
                ('task1IS56', models.BooleanField(default=False, verbose_name='SI.5.6 Actualiza el Registro de Trazabilidad, si corresponde.')),
                ('task1IS57', models.BooleanField(default=False, verbose_name='SI.5.7 Documentar la *Guía de Operación del Producto o actualizar la guía actual, si corresponde. *(Opcional)')),
                ('task1IS58', models.BooleanField(default=False, verbose_name='SI.5.8 Verificar y obtener aprobación de la *Guía de Operación del Producto, si corresponde (ver SI.5.7)')),
                ('task1IS59', models.BooleanField(default=False, verbose_name='SI.5.9 Documentar la *Documentación de Usuario del Software o actualizar la actual, si corresponde. *(Opcional)')),
                ('task1IS510', models.BooleanField(default=False, verbose_name='SI.5.10 Verificar y obtener aprobación de la *Documentación del Usuario del Software, si corresponde (ver SI.5.9)')),
                ('task1IS511', models.BooleanField(default=False, verbose_name='SI.5.11 Incorporar los Casos de Prueba y Procedimientos de Prueba, Software, Registro de Trazabilidad, Informe de Prueba, *Guía de Operación del Producto y *Documentación del Usuario del Software a la Configuración del Software como parte de la línea base. *(Opcional)')),
                ('task1IS61', models.BooleanField(default=False, verbose_name='SI.6.1 Asignar Tareas a los miembros del equipo de trabajo relacionadas con su rol, de acuerdo al Plan de Proyecto vigente.')),
                ('task1IS62', models.BooleanField(default=False, verbose_name='SI.6.2 Comprender la configuración del software.')),
                ('task1IS63', models.BooleanField(default=False, verbose_name='SI.6.3 Documentar la Documentación de Mantenimiento o actualizar la actual.')),
                ('task1IS64', models.BooleanField(default=False, verbose_name='SI.6.4 Verificar y obtener la aprobación de la Documentación de Mantenimiento.')),
                ('task1IS65', models.BooleanField(default=False, verbose_name='SI.6.5 Incorporar la Documentación de Mantenimiento como base para la Configuración del Software.')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guiadevopsapp.usuariomodel')),
            ],
            options={
                'get_latest_by': ['fecha'],
            },
        ),
    ]
