"""guiadevopsapp URL Configuration"""
from django.urls import path, include
from . import views

urlpatterns = [
    path('inicio/', views.home, name='home'),
    path('accounts/', include('allauth.urls')),
    path('', views.inicio, name='inicio'),
    path('indexdash/', views.iniciodash, name='indexdash'),
    path('actividades/', views.actividades, name='actividades'),
    path('planificacion/', views.planificacion, name='planificacion'),
    path('planificacion/tareas/', views.planificaciontareas, name='planificaciontareas'),
    path('planificacion/herramientas/', views.planificacionherramientas, name='planificacionherramientas'),
    path('planificacion/practicas/', views.planificacionpracticas, name='planificacionpracticas'),
    path('perfilusuario/', views.perfilusuario, name='perfilusuario'),
    path('codificacion/', views.codificacion, name='codificacion'),
    path('codificacion/tareas/', views.codificaciontareas, name='codificaciontareas'),
    path('codificacion/herramientas/', views.codificacionherramientas, name='codificacionherramientas'),
    path('codificacion/practicas/', views.codificacionpracticas, name='codificacionpracticas'),
    path('construccion/', views.construccion, name='construccion'),
    path('construccion/tareas/', views.construcciontareas, name='construcciontareas'),
    path('construccion/herramientas/', views.construccionherramientas, name='construccionherramientas'),
    path('construccion/practicas/', views.construccionpracticas, name='construccionpracticas'),
    path('pruebas/', views.pruebas, name='pruebas'),
    path('pruebas/tareas/', views.pruebastareas, name='pruebastareas'),
    path('pruebas/herramientas/', views.pruebasherramientas, name='pruebasherramientas'),
    path('pruebas/practicas/', views.pruebaspracticas, name='pruebaspracticas'),
    path('liberacion/', views.liberacion, name='liberacion'),
    path('liberacion/tareas/', views.liberaciontareas, name='liberaciontareas'),
    path('liberacion/herramientas/', views.liberacionherramientas, name='liberacionherramientas'),
    path('liberacion/practicas/', views.liberacionpracticas, name='liberacionpracticas'),
    path('despliegue/', views.despliegue, name='despliegue'),
    path('despliegue/tareas/', views.desplieguetareas, name='desplieguetareas'),
    path('despliegue/herramientas/', views.despliegueherramientas, name='despliegueherramientas'),
    path('despliegue/practicas/', views.desplieguepracticas, name='desplieguepracticas'),
    path('operaciones/', views.operaciones, name='operaciones'),
    path('operaciones/tareas/', views.operacionestareas, name='operacionestareas'),
    path('operaciones/herramientas/', views.operacionesherramientas, name='operacionesherramientas'),
    path('operaciones/practicas/', views.operacionespracticas, name='operacionespracticas'),
    path('monitoreo/', views.monitoreo, name='monitoreo'),
    path('monitoreo/tareas/', views.monitoreotareas, name='monitoreotareas'),
    path('monitoreo/herramientas/', views.monitoreoherramientas, name='monitoreoherramientas'),
    path('monitoreo/practicas/', views.monitoreopracticas, name='monitoreopracticas'),
    path('referencias/', views.referencias, name='referencias'),
]
